services:
  db:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - ./data:/var/lib/postgresql/data