# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-vector',
                'doc_host': 'https://timescale.github.io',
                'git_url': 'https://github.com/timescale/python-vector',
                'lib_path': 'python_vector'},
  'syms': {'python_vector.core': {'python_vector.core.foo': ('vector.html#foo', 'python_vector/core.py')}}}
