from collections.abc import ItemsView, Iterator, KeysView, Mapping, Sequence, ValuesView
from typing import Any, Protocol, TypeVar

from psycopg2.extensions import cursor

class DictCursor(cursor, Protocol):
    def __init__(self) -> None: ...

def register_uuid(oids: int | None = None, conn_or_curs: cursor | None = None) -> None: ...

T = TypeVar("T")

class RealDictRow(Mapping[str, Any]):
    """A row of database results that allows both sequence and mapping access."""

    def __init__(self, row: Sequence[Any], cursor: Any) -> None: ...
    def __getitem__(self, key: str | int) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def get(self, key: str, default: T = None) -> Any | T: ...
    def items(self) -> ItemsView[str, Any]: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def __getattr__(self, name: str) -> Any: ...
