name: Ruff Linting and Formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install uv
      run: pip install uv
    - name: Create venv
      run: uv venv
    - name: Install dependencies
      run: |
        uv pip install .
        uv pip install .[dev]
    - name: Run Ruff linter
      run: uv run ruff check .
    - name: Run Ruff formatter
      run: uv run ruff format . --check