name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install uv
      run: pip install uv
    - name: Create venv
      run: uv venv
    - name: Install dependencies
      run: |
        uv pip install .
        uv pip install .[dev]
    - name: Start docker-compose 
      run: docker compose up -d
    - name: Run Test
      run: uv run pytest
    - name: Logs
      run: docker compose logs
    - name: Stop docker-compose
      run: docker compose down